// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data_fetch_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250427183121_CreateInitialTables1")]
    partial class CreateInitialTables1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "klant_id");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "adres");

                    b.Property<string>("Bedrijf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bedrijf");

                    b.Property<string>("Contactpersoon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "contactpersoon");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "telefoonnummer");

                    b.HasKey("CustomerId");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("Models.Employee", b =>
                {
                    b.Property<int>("MedewerkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "medewerker_id");

                    b.Property<bool>("Beschikbaar")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "beschikbaar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "naam");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<int?>("VoertuigId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("MedewerkerId");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("Models.Location", b =>
                {
                    b.Property<int>("LocatieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "locatie_id");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "adres");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "land");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "postcode");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "stad");

                    b.HasKey("LocatieId");

                    b.ToTable("Locaties");
                });

            modelBuilder.Entity("Models.Trip", b =>
                {
                    b.Property<int>("RitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AfstandKm")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "afstand_km");

                    b.Property<int>("BestemmingId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "bestemming_id");

                    b.Property<int>("BrandstofVerbruikL")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "brandstof_verbruik_l");

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "chauffeur_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "datum");

                    b.Property<int>("DuurMinuten")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "duur_minuten");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "klant_id");

                    b.Property<string>("RitNummer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "rit_id");

                    b.Property<int>("VehicleVoertuigId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("RitId");

                    b.HasIndex("VehicleVoertuigId");

                    b.ToTable("Ritten");

                    b.HasAnnotation("Relational:JsonPropertyName", "ritten");
                });

            modelBuilder.Entity("Models.Vehicle", b =>
                {
                    b.Property<int>("VoertuigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandstofType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brandstof_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Kenteken")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "kenteken");

                    b.Property<int>("MaximaleCapaciteitKg")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "maximale_capaciteit_kg");

                    b.Property<string>("Merk")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "merk");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "model");

                    b.Property<string>("VoertuigNummer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("VoertuigId");

                    b.ToTable("Voertuigen");
                });

            modelBuilder.Entity("Models.Zending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("CurrentLoadKg")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "huidige_capaciteit");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bestemming");

                    b.Property<int>("EmptyKilometers")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "onbenutte_kilometers");

                    b.Property<int>("MaxCapacityKg")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "max_capaciteit");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "zending_id");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("Id");

                    b.ToTable("Zendingen");
                });

            modelBuilder.Entity("Models.Trip", b =>
                {
                    b.HasOne("Models.Vehicle", "Vehicle")
                        .WithMany("Ritten")
                        .HasForeignKey("VehicleVoertuigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Models.Vehicle", b =>
                {
                    b.Navigation("Ritten");
                });
#pragma warning restore 612, 618
        }
    }
}
