// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data_fetch_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Models.Zending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLoadKg")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "huidige_capaciteit");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bestemming");

                    b.Property<int>("EmptyKilometers")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "onbenutte-kilometers");

                    b.Property<int>("MaxCapacityKg")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "max_capaciteit");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "zending_id");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("Id");

                    b.ToTable("Zendingen");
                });

            modelBuilder.Entity("Rit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AfstandKm")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "afstand_km");

                    b.Property<int>("BrandstofVerbruikL")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "brandstof_verbruik_l");

                    b.Property<string>("Datum")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "datum");

                    b.Property<int>("GemiddeldVerbruikPer100Km")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "gemiddeld_verbruik_l_per_100km");

                    b.Property<string>("RitId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "rit_id");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Ritten");

                    b.HasAnnotation("Relational:JsonPropertyName", "ritten");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandstofType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brandstof_type");

                    b.Property<string>("Kenteken")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "kenteken");

                    b.Property<string>("Merk")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "merk");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "model");

                    b.Property<string>("VoertuigId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "voertuig_id");

                    b.HasKey("Id");

                    b.ToTable("Voertuigen");
                });

            modelBuilder.Entity("Rit", b =>
                {
                    b.HasOne("Vehicle", null)
                        .WithMany("Ritten")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Navigation("Ritten");
                });
#pragma warning restore 612, 618
        }
    }
}
