name: .NET CI

on:
  push:
    branches: [ "CICD" ]
  pull_request:
    branches: [ "CICD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./prototype/data-fetch-api

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./prototype/data-fetch-api

    - name: Run (with timeout)
      run: timeout 10s dotnet run
      working-directory: ./prototype/data-fetch-api

